version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8085:80
    environment:
      MYSQL_DATABASE: mywordpress
      MYSQL_USER: Veronica
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: '12345'
    volumes:
      - db:/var/lib/mysql

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mywordpress
      MYSQL_USER: Veronica
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: '12345'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:


