# Este es un workflow básico para ayudarte a comenzar con GitHub Actions

name: CI

# Controla cuándo se ejecutará el workflow
on:
  # Ejecuta el workflow en eventos de push o pull request en la rama "main"
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Un workflow está compuesto de uno o más jobs que pueden ejecutarse secuencialmente o en paralelo
jobs:
  # Este workflow contiene un job llamado "build"
  build:
    # El tipo de runner en el que se ejecutará el job
    runs-on: ubuntu-latest

    # Pasos que se ejecutarán como parte del job
    steps:
      # Descarga tu repositorio en $GITHUB_WORKSPACE para que los pasos puedan acceder a él
      - uses: actions/checkout@v4

      # Ejecuta un conjunto de comandos
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # Este es el nuevo job llamado "deploy"
  deploy:
    runs-on: ubuntu-latest

    # Pasos para el job deploy
    steps:
      - name: Deployment
        run: echo "Hola, yo soy el job que despliega la API"
