name: CI

on:
 
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Hola, yo soy el job que despliega la API"

  clonar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar
        run: git clone --branch develop  https://github.com/Veronicachase/devops-primera-clase.git

  instalar:
    runs-on: ubuntu-latest
    steps:
      run: |
          cd back
          npm install

  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "Hola"

  testear:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar tests
        run: |
          cd back
          npm run test