name: CI

on:
 
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  # Este workflow contiene un job llamado "build"
  build:
    # El tipo de runner en el que se ejecutará el job
    runs-on: ubuntu-latest

    # Pasos que se ejecutarán como parte del job
    steps:
      # Descarga tu repositorio en $GITHUB_WORKSPACE para que los pasos puedan acceder a él
      - uses: actions/checkout@v4

      # Ejecuta un conjunto de comandos
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Hola"

  clonar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar
        run: git clone --branch develop  https://github.com/Veronicachase/devops-primera-clase.git

  instalar:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias
        run: |
            cd back
            npm install

  
  testear:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar tests
        run: |
          cd back
          npm run test