name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  mailService:
    runs-on: ubuntu-latest
    steps:
      # Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop
      # Instalar dependencias de mailService
      - name: Instalar dependencias mailService
        run: |
          cd mailService
          npm install

      # Ejecutar tests en mailService
      - name: Ejecutar tests mailService
        run: |
          cd mailService
          npm run test

      # Mensaje informativo
      - name: Hola desde mailService
        run: echo "Pruebas completadas para mailService, hola"

  userService:
    runs-on: ubuntu-latest
    steps:
      # Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      # Instalar dependencias de userService
      - name: Instalar dependencias userService
        run: |
          cd userService
          npm install

      # Ejecutar tests en userService
      - name: Ejecutar tests userService
        run: |
          cd userService
          npm run test

      # Mensaje informativo
      - name: Hola desde userService
        run: echo "Pruebas completadas para userService"
